title: 歌回救星 2.0 使用說明
description: Singing Stream Savior 2.0.5.1 繁體中文使用說明
lang: zh-TW
timezone: Asia/Taipei
url: https://noonisawesome.github.io
baseurl: /Singing-Stream-Savior-Manual

analytics:
  production_host: noonisawesome.github.io
  pageview_endpoint: https://api.counterapi.dev/v1/noonisawesome-singing-stream-savior-manual/pageviews/up

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-seo-tag
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - assets/README.md
  - scripts
